const STORE_GAME = 'STORE_GAME';
const FETCH_MOVE_SUCCEED = 'FETCH_MOVE_SUCCEED';
const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';
const RESET_GAME = 'RESET_GAME';
const LOG_MOVE = 'LOG_MOVE';

export { STORE_GAME, CHANGE_VIEW_TYPE, RESET_GAME, LOG_MOVE, FETCH_MOVE_SUCCEED };